; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	speck128_encryptx
;	COMDAT pdata
; File c:\hub\speck\speck128.c
pdata	SEGMENT
$pdata$speck128_encryptx DD imagerel $LN8
	DD	imagerel $LN8+108
	DD	imagerel $unwind$speck128_encryptx
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$speck128_encryptx DD 040a01H
	DD	02740aH
	DD	013405H
; Function compile flags: /Ogspy
xdata	ENDS
;	COMDAT speck128_encryptx
_TEXT	SEGMENT
key$ = 8
in$ = 16
speck128_encryptx PROC					; COMDAT
; Line 93
$LN8:
	mov	QWORD PTR [rsp+8], rbx
	mov	QWORD PTR [rsp+16], rdi
; Line 97
	mov	r9, QWORD PTR [rcx]
; Line 98
	mov	r10, QWORD PTR [rcx+8]
; Line 99
	mov	rbx, QWORD PTR [rcx+16]
; Line 100
	mov	rdi, QWORD PTR [rcx+24]
; Line 103
	mov	r8, QWORD PTR [rdx]
; Line 104
	mov	rcx, QWORD PTR [rdx+8]
; Line 106
	xor	r11d, r11d
$LL3@speck128_e:
; Line 109
	ror	rcx, 8
	add	rcx, r8
	xor	rcx, r9
; Line 110
	rol	r8, 3
	xor	r8, rcx
; Line 113
	ror	r10, 8
	add	r10, r9
	xor	r10, r11
; Line 114
	rol	r9, 3
	inc	r11
	xor	r9, r10
	mov	rax, r10
; Line 116
	mov	r10, rbx
	mov	rbx, rdi
; Line 117
	mov	rdi, rax
	cmp	r11, 34					; 00000022H
	jb	SHORT $LL3@speck128_e
; Line 122
	mov	rbx, QWORD PTR [rsp+8]
	mov	rdi, QWORD PTR [rsp+16]
	mov	QWORD PTR [rdx], r8
	mov	QWORD PTR [rdx+8], rcx
	ret	0
speck128_encryptx ENDP
_TEXT	ENDS
END
