; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	c:\hub\speck\speck64.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_speck64_encryptx
; Function compile flags: /Ogspy
;	COMDAT _speck64_encryptx
_TEXT	SEGMENT
_t$ = -8						; size = 4
_k2$ = -4						; size = 4
_k3$ = 8						; size = 4
_key$ = 8						; size = 4
_i$ = 12						; size = 4
_in$ = 12						; size = 4
_speck64_encryptx PROC					; COMDAT
; File c:\hub\speck\speck64.c
; Line 92
	push	ebp
	mov	ebp, esp
	push	ecx
	push	ecx
; Line 96
	mov	ecx, DWORD PTR _key$[ebp]
	mov	edx, DWORD PTR [ecx]
; Line 97
	mov	eax, DWORD PTR [ecx+4]
	push	ebx
	push	esi
; Line 98
	mov	esi, DWORD PTR [ecx+8]
; Line 99
	mov	ecx, DWORD PTR [ecx+12]
	mov	DWORD PTR _k3$[ebp], ecx
; Line 102
	mov	ecx, DWORD PTR _in$[ebp]
; Line 105
	and	DWORD PTR _i$[ebp], 0
	push	edi
	mov	edi, DWORD PTR [ecx+4]
	mov	DWORD PTR _k2$[ebp], esi
	mov	esi, DWORD PTR [ecx]
$LL3@speck64_en:
; Line 116
	mov	ebx, DWORD PTR _k3$[ebp]
	ror	esi, 8
	add	esi, edi
	xor	esi, edx
	rol	edi, 3
	xor	edi, esi
	ror	eax, 8
	add	eax, edx
	xor	eax, DWORD PTR _i$[ebp]
	mov	DWORD PTR _t$[ebp], ebx
	mov	ebx, DWORD PTR _k2$[ebp]
	mov	DWORD PTR _k3$[ebp], ebx
	mov	ebx, DWORD PTR _t$[ebp]
	rol	edx, 3
	xor	edx, eax
	inc	DWORD PTR _i$[ebp]
	cmp	DWORD PTR _i$[ebp], 27			; 0000001bH
	mov	DWORD PTR _k2$[ebp], ebx
; Line 117
	mov	ebx, DWORD PTR _k3$[ebp]
	mov	DWORD PTR _k3$[ebp], eax
	mov	eax, ebx
	jb	SHORT $LL3@speck64_en
; Line 121
	mov	DWORD PTR [ecx+4], edi
	pop	edi
	mov	DWORD PTR [ecx], esi
	pop	esi
	pop	ebx
; Line 122
	leave
	ret	0
_speck64_encryptx ENDP
_TEXT	ENDS
END
