; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\odzhan\speck\speck.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_speck_setkey
; Function compile flags: /Ogspy
;	COMDAT _speck_setkey
_TEXT	SEGMENT
_in$ = 8						; size = 4
_ks$ = 12						; size = 4
_speck_setkey PROC					; COMDAT
; File c:\odzhan\speck\speck.c
; Line 37
	mov	edx, DWORD PTR _in$[esp-4]
	mov	ecx, DWORD PTR [edx]
; Line 38
	mov	eax, DWORD PTR [edx+4]
	push	ebx
	push	esi
	push	edi
; Line 39
	mov	edi, DWORD PTR [edx+8]
; Line 40
	mov	edx, DWORD PTR [edx+12]
; Line 43
	xor	esi, esi
$LL3@speck_setk:
; Line 45
	mov	ebx, DWORD PTR _ks$[esp+8]
; Line 47
	ror	eax, 8
	add	eax, ecx
	xor	eax, esi
	mov	DWORD PTR [ebx+esi*4], ecx
; Line 48
	rol	ecx, 3
	xor	ecx, eax
; Line 51
	mov	ebx, edi
	inc	esi
	mov	edi, edx
; Line 52
	mov	edx, eax
	mov	eax, ebx
	cmp	esi, 26					; 0000001aH
	jb	SHORT $LL3@speck_setk
; Line 54
	pop	edi
	pop	esi
	pop	ebx
	ret	0
_speck_setkey ENDP
_TEXT	ENDS
PUBLIC	_speck_encrypt
; Function compile flags: /Ogspy
;	COMDAT _speck_encrypt
_TEXT	SEGMENT
_keys$ = 8						; size = 4
_enc$ = 12						; size = 4
tv186 = 16						; size = 4
_in$ = 16						; size = 4
_speck_encrypt PROC					; COMDAT
; Line 57
	push	ebp
	mov	ebp, esp
; Line 62
	mov	eax, DWORD PTR _in$[ebp]
	mov	ecx, DWORD PTR [eax]
; Line 63
	mov	edx, DWORD PTR [eax+4]
	push	ebx
	push	esi
	mov	esi, DWORD PTR _keys$[ebp]
	push	edi
	mov	edi, esi
	add	esi, 104				; 00000068H
	mov	DWORD PTR tv186[ebp], 27		; 0000001bH
$LL10@speck_encr:
; Line 67
	cmp	DWORD PTR _enc$[ebp], 1
	jne	SHORT $LN2@speck_encr
; Line 69
	xor	edx, ecx
; Line 70
	xor	ecx, DWORD PTR [esi]
	ror	edx, 3
	sub	ecx, edx
	rol	ecx, 8
; Line 71
	jmp	SHORT $LN4@speck_encr
$LN2@speck_encr:
; Line 72
	ror	ecx, 8
	add	ecx, edx
	xor	ecx, DWORD PTR [edi]
; Line 73
	rol	edx, 3
	xor	edx, ecx
$LN4@speck_encr:
; Line 65
	sub	esi, 4
	add	edi, 4
	dec	DWORD PTR tv186[ebp]
	jne	SHORT $LL10@speck_encr
; Line 77
	pop	edi
	pop	esi
	mov	DWORD PTR [eax], ecx
; Line 78
	mov	DWORD PTR [eax+4], edx
	pop	ebx
; Line 79
	pop	ebp
	ret	0
_speck_encrypt ENDP
_TEXT	ENDS
END
